# Generated by Django 3.2.9 on 2022-04-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photodata',
            name='user',
        ),
        migrations.AddField(
            model_name='photodata',
            name='userId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photodata',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
